export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = 'customer' | 'sale' | 'owner' | 'admin';
export type KYCStatus = 'pending' | 'submitted' | 'approved' | 'rejected';
export type RoomStatus = 'available' | 'deposited' | 'rented' | 'maintenance';
export type RoomType = 'chung_cu_mini' | 'studio' | '1n1k' | '2n1k' | 'ccmn_cao_cap' | 'can_ho_dich_vu';
export type LeadStatus = 'new' | 'consulting' | 'scheduled' | 'viewed' | 'deposited' | 'success' | 'cancelled';
export type AppointmentStatus = 'scheduled' | 'confirmed' | 'checked_in' | 'completed' | 'cancelled' | 'no_show';
export type DepositStatus = 'pending' | 'approved' | 'rejected' | 'cancelled' | 'refunded';
export type CommissionStatus = 'pending' | 'approved' | 'paid';
export type SaleAssignmentStatus = 'pending' | 'approved' | 'rejected' | 'inactive';
export type SaleRank = 'ctv' | 'bronze' | 'silver' | 'gold' | 'platinum' | 'diamond';
export type DisputeStatus = 'open' | 'investigating' | 'resolved' | 'closed' | 'escalated';
export type DisputePriority = 'low' | 'normal' | 'high' | 'urgent';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          avatar_url: string | null;
          role: UserRole;
          kyc_status: KYCStatus;
          cccd_front_url: string | null;
          cccd_back_url: string | null;
          face_verification_url: string | null;
          kyc_submitted_at: string | null;
          kyc_approved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          role?: UserRole;
          kyc_status?: KYCStatus;
          cccd_front_url?: string | null;
          cccd_back_url?: string | null;
          face_verification_url?: string | null;
          kyc_submitted_at?: string | null;
          kyc_approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          role?: UserRole;
          kyc_status?: KYCStatus;
          cccd_front_url?: string | null;
          cccd_back_url?: string | null;
          face_verification_url?: string | null;
          kyc_submitted_at?: string | null;
          kyc_approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      buildings: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          address: string;
          district: string;
          description: string | null;
          total_floors: number;
          total_rooms: number;
          amenities: string[] | null;
          images: string[] | null;
          latitude: number | null;
          longitude: number | null;
          occupancy_rate: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          address: string;
          district: string;
          description?: string | null;
          total_floors?: number;
          total_rooms?: number;
          amenities?: string[] | null;
          images?: string[] | null;
          latitude?: number | null;
          longitude?: number | null;
          occupancy_rate?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          address?: string;
          district?: string;
          description?: string | null;
          total_floors?: number;
          total_rooms?: number;
          amenities?: string[] | null;
          images?: string[] | null;
          latitude?: number | null;
          longitude?: number | null;
          occupancy_rate?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      rooms: {
        Row: {
          id: string;
          building_id: string;
          owner_id: string;
          room_number: string;
          floor: number;
          area: number;
          price: number;
          room_type: RoomType;
          status: RoomStatus;
          amenities: string[] | null;
          images: string[] | null;
          description: string | null;
          video_url: string | null;
          deposit_amount: number | null;
          monthly_fee: number | null;
          electricity_price: number | null;
          water_price: number | null;
          internet_price: number | null;
          available_date: string | null;
          last_contacted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          building_id: string;
          owner_id: string;
          room_number: string;
          floor?: number;
          area: number;
          price: number;
          room_type?: RoomType;
          status?: RoomStatus;
          amenities?: string[] | null;
          images?: string[] | null;
          description?: string | null;
          video_url?: string | null;
          deposit_amount?: number | null;
          monthly_fee?: number | null;
          electricity_price?: number | null;
          water_price?: number | null;
          internet_price?: number | null;
          available_date?: string | null;
          last_contacted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          building_id?: string;
          owner_id?: string;
          room_number?: string;
          floor?: number;
          area?: number;
          price?: number;
          room_type?: RoomType;
          status?: RoomStatus;
          amenities?: string[] | null;
          images?: string[] | null;
          description?: string | null;
          video_url?: string | null;
          deposit_amount?: number | null;
          monthly_fee?: number | null;
          electricity_price?: number | null;
          water_price?: number | null;
          internet_price?: number | null;
          available_date?: string | null;
          last_contacted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          sale_id: string;
          room_id: string | null;
          customer_name: string;
          customer_phone: string;
          customer_email: string | null;
          customer_note: string | null;
          status: LeadStatus;
          source: string | null;
          interested_districts: string[] | null;
          interested_price_range: string | null;
          interested_area_range: string | null;
          last_contacted_at: string | null;
          next_follow_up_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sale_id: string;
          room_id?: string | null;
          customer_name: string;
          customer_phone: string;
          customer_email?: string | null;
          customer_note?: string | null;
          status?: LeadStatus;
          source?: string | null;
          interested_districts?: string[] | null;
          interested_price_range?: string | null;
          interested_area_range?: string | null;
          last_contacted_at?: string | null;
          next_follow_up_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sale_id?: string;
          room_id?: string | null;
          customer_name?: string;
          customer_phone?: string;
          customer_email?: string | null;
          customer_note?: string | null;
          status?: LeadStatus;
          source?: string | null;
          interested_districts?: string[] | null;
          interested_price_range?: string | null;
          interested_area_range?: string | null;
          last_contacted_at?: string | null;
          next_follow_up_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          lead_id: string;
          sale_id: string;
          room_id: string;
          customer_name: string;
          customer_phone: string;
          scheduled_at: string;
          status: AppointmentStatus;
          notes: string | null;
          check_in_lat: number | null;
          check_in_lng: number | null;
          check_in_at: string | null;
          check_in_photo_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          sale_id: string;
          room_id: string;
          customer_name: string;
          customer_phone: string;
          scheduled_at: string;
          status?: AppointmentStatus;
          notes?: string | null;
          check_in_lat?: number | null;
          check_in_lng?: number | null;
          check_in_at?: string | null;
          check_in_photo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          sale_id?: string;
          room_id?: string;
          customer_name?: string;
          customer_phone?: string;
          scheduled_at?: string;
          status?: AppointmentStatus;
          notes?: string | null;
          check_in_lat?: number | null;
          check_in_lng?: number | null;
          check_in_at?: string | null;
          check_in_photo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      deposits: {
        Row: {
          id: string;
          room_id: string;
          sale_id: string;
          owner_id: string;
          lead_id: string | null;
          customer_name: string;
          customer_phone: string;
          customer_email: string | null;
          customer_cccd_front_url: string | null;
          customer_cccd_back_url: string | null;
          deposit_amount: number;
          transfer_receipt_url: string | null;
          notes: string | null;
          owner_notes: string | null;
          status: DepositStatus;
          approved_at: string | null;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          sale_id: string;
          owner_id: string;
          lead_id?: string | null;
          customer_name: string;
          customer_phone: string;
          customer_email?: string | null;
          customer_cccd_front_url?: string | null;
          customer_cccd_back_url?: string | null;
          deposit_amount: number;
          transfer_receipt_url?: string | null;
          notes?: string | null;
          owner_notes?: string | null;
          status?: DepositStatus;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          sale_id?: string;
          owner_id?: string;
          lead_id?: string | null;
          customer_name?: string;
          customer_phone?: string;
          customer_email?: string | null;
          customer_cccd_front_url?: string | null;
          customer_cccd_back_url?: string | null;
          deposit_amount?: number;
          transfer_receipt_url?: string | null;
          notes?: string | null;
          owner_notes?: string | null;
          status?: DepositStatus;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      commissions: {
        Row: {
          id: string;
          deposit_id: string;
          sale_id: string;
          owner_id: string;
          room_id: string;
          commission_rate: number;
          commission_amount: number;
          status: CommissionStatus;
          paid_at: string | null;
          paid_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          deposit_id: string;
          sale_id: string;
          owner_id: string;
          room_id: string;
          commission_rate: number;
          commission_amount: number;
          status?: CommissionStatus;
          paid_at?: string | null;
          paid_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          deposit_id?: string;
          sale_id?: string;
          owner_id?: string;
          room_id?: string;
          commission_rate?: number;
          commission_amount?: number;
          status?: CommissionStatus;
          paid_at?: string | null;
          paid_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      sale_assignments: {
        Row: {
          id: string;
          sale_id: string;
          building_id: string;
          owner_id: string;
          status: SaleAssignmentStatus;
          commission_rate: number;
          is_primary: boolean;
          total_deals: number;
          total_commission: number;
          rating: number;
          response_rate: number;
          applied_at: string;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sale_id: string;
          building_id: string;
          owner_id: string;
          status?: SaleAssignmentStatus;
          commission_rate?: number;
          is_primary?: boolean;
          total_deals?: number;
          total_commission?: number;
          rating?: number;
          response_rate?: number;
          applied_at?: string;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sale_id?: string;
          building_id?: string;
          owner_id?: string;
          status?: SaleAssignmentStatus;
          commission_rate?: number;
          is_primary?: boolean;
          total_deals?: number;
          total_commission?: number;
          rating?: number;
          response_rate?: number;
          applied_at?: string;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      sale_rankings: {
        Row: {
          id: string;
          sale_id: string;
          rank: SaleRank;
          score: number;
          successful_deals: number;
          total_leads: number;
          conversion_rate: number;
          total_commission_earned: number;
          monthly_leads_target: number;
          monthly_deals_target: number;
          current_month_leads: number;
          current_month_deals: number;
          last_activity_at: string | null;
          promoted_at: string | null;
          demoted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sale_id: string;
          rank?: SaleRank;
          score?: number;
          successful_deals?: number;
          total_leads?: number;
          conversion_rate?: number;
          total_commission_earned?: number;
          monthly_leads_target?: number;
          monthly_deals_target?: number;
          current_month_leads?: number;
          current_month_deals?: number;
          last_activity_at?: string | null;
          promoted_at?: string | null;
          demoted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sale_id?: string;
          rank?: SaleRank;
          score?: number;
          successful_deals?: number;
          total_leads?: number;
          conversion_rate?: number;
          total_commission_earned?: number;
          monthly_leads_target?: number;
          monthly_deals_target?: number;
          current_month_leads?: number;
          current_month_deals?: number;
          last_activity_at?: string | null;
          promoted_at?: string | null;
          demoted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      disputes: {
        Row: {
          id: string;
          room_id: string | null;
          deposit_id: string | null;
          reporter_id: string;
          reported_id: string | null;
          type: string;
          priority: DisputePriority;
          status: DisputeStatus;
          title: string;
          description: string;
          evidence_urls: string[] | null;
          resolution_notes: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          room_id?: string | null;
          deposit_id?: string | null;
          reporter_id: string;
          reported_id?: string | null;
          type: string;
          priority?: DisputePriority;
          status?: DisputeStatus;
          title: string;
          description: string;
          evidence_urls?: string[] | null;
          resolution_notes?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          room_id?: string | null;
          deposit_id?: string | null;
          reporter_id?: string;
          reported_id?: string | null;
          type?: string;
          priority?: DisputePriority;
          status?: DisputeStatus;
          title?: string;
          description?: string;
          evidence_urls?: string[] | null;
          resolution_notes?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      activity_logs: {
        Row: {
          id: string;
          user_id: string;
          entity_type: string;
          entity_id: string | null;
          action: string;
          old_values: Json | null;
          new_values: Json | null;
          metadata: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          entity_type: string;
          entity_id?: string | null;
          action: string;
          old_values?: Json | null;
          new_values?: Json | null;
          metadata?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          entity_type?: string;
          entity_id?: string | null;
          action?: string;
          old_values?: Json | null;
          new_values?: Json | null;
          metadata?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
