import type { Database } from './database.types';

type Building = Database['public']['Tables']['buildings']['Row'];
type Room = Database['public']['Tables']['rooms']['Row'] & { building?: Building };

export const sampleBuildings: Building[] = [
  {
    id: '1',
    owner_id: 'owner-1',
    name: 'Tòa nhà Home Cầu Giấy',
    address: 'Số 18 Ngõ 82 Dịch Vọng Hậu, Cầu Giấy, Hà Nội',
    district: 'Cầu Giấy',
    description: 'Tòa nhà cao cấp với đầy đủ tiện nghi, an ninh 24/7, gần trường đại học và siêu thị. Thiết kế hiện đại, không gian thoáng đãng.',
    total_floors: 6,
    total_rooms: 30,
    amenities: ['Thang máy', 'Camera an ninh', 'Khóa vân tay', 'Chỗ để xe', 'Bếp chung'],
    images: [
      'https://images.unsplash.com/photo-1522708323538-fba64bf76648?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3ae89?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    latitude: 21.0317,
    longitude: 105.7957,
    occupancy_rate: 75.5,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    owner_id: 'owner-1',
    name: 'Nhà trọ Thanh Xuân Premium',
    address: 'Ngõ 450 Nguyễn Trãi, Thanh Xuân, Hà Nội',
    district: 'Thanh Xuân',
    description: 'Không gian thoáng đãng, gần metro, nhiều tiện ích xung quanh. Phù hợp cho sinh viên và người đi làm.',
    total_floors: 4,
    total_rooms: 20,
    amenities: ['Chỗ để xe', 'Bếp chung', 'Máy giặt chung', 'Thang máy', 'Camera an ninh'],
    images: [
      'https://images.unsplash.com/photo-1502672023488-07e099e25e68?w=800',
      'https://images.unsplash.com/photo-1515263489006-61c0a13a153f?w=800',
    ],
    latitude: 20.9985,
    longitude: 105.8036,
    occupancy_rate: 82.0,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    owner_id: 'owner-1',
    name: 'CCMN Long Biên Riverside',
    address: 'Số 25 Ngô Xuân Quảng, Long Biên, Hà Nội',
    district: 'Long Biên',
    description: 'View sông Hồng, không gian xanh, yên tĩnh, gần cầu Nhật Tân. Căn hộ dịch vụ cao cấp với đầy đủ nội thất.',
    total_floors: 7,
    total_rooms: 35,
    amenities: ['Thang máy', 'Camera an ninh', 'Khóa vân tay', 'Chỗ để xe', 'Gym', 'Ban công'],
    images: [
      'https://images.unsplash.com/photo-1460317212962-ffa3c17c6b5e?w=800',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
    ],
    latitude: 21.0417,
    longitude: 105.8747,
    occupancy_rate: 68.0,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    owner_id: 'owner-2',
    name: 'Tòa CCMN Xa La Hà Đông',
    address: 'Khu đô thị Xa La, Hà Đông, Hà Nội',
    district: 'Hà Đông',
    description: 'Khu vực yên tĩnh, gần các trường đại học kinh tế, xây dựng. Giá cả hợp lý, phục vụ chính sinh viên.',
    total_floors: 5,
    total_rooms: 25,
    amenities: ['Chỗ để xe', 'Bếp chung', 'Máy giặt chung', 'Camera an ninh'],
    images: [
      'https://images.unsplash.com/photo-1534237710431-e2fc698436d0?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add721a?w=800',
    ],
    latitude: 20.9561,
    longitude: 105.7424,
    occupancy_rate: 90.0,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    owner_id: 'owner-2',
    name: 'Chung cư Mini Đống Đa',
    address: 'Ngõ 275 Đường Láng, Đống Đa, Hà Nội',
    district: 'Đống Đa',
    description: 'Vị trí trung tâm, dễ di chuyển các quận. Phòng đẹp, sạch sẽ, an ninh đảm bảo.',
    total_floors: 4,
    total_rooms: 16,
    amenities: ['Thang máy', 'Camera an ninh', 'Chỗ để xe', 'Bếp riêng'],
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    latitude: 21.0157,
    longitude: 105.8147,
    occupancy_rate: 100.0,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    owner_id: 'owner-3',
    name: 'Tòa nhà Tây Hồ View',
    address: 'Đường Xuân La, Tây Hồ, Hà Nội',
    district: 'Tây Hồ',
    description: 'Căn hộ cao cấp với view Hồ Tây, không gian xanh, phù hợp cho chuyên gia và người nước ngoài.',
    total_floors: 8,
    total_rooms: 40,
    amenities: ['Thang máy', 'Camera an ninh', 'Khóa vân tay', 'Chỗ để xe', 'Gym', 'Hồ bơi', 'Ban công'],
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1c3a397171?w=800',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800',
    ],
    latitude: 21.0717,
    longitude: 105.8044,
    occupancy_rate: 45.0,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const sampleRooms: Room[] = [
  // Building 1 - Cầu Giấy
  {
    id: 'room-1',
    building_id: '1',
    owner_id: 'owner-1',
    room_number: '101',
    floor: 1,
    area: 25,
    price: 3500000,
    room_type: 'studio',
    status: 'available',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo', 'Tủ lạnh', 'Ban công'],
    images: [
      'https://images.unsplash.com/photo-1522708323538-fba64bf76648?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    description: 'Phòng studio đẹp, có ban công rộng, đầy đủ nội thất.',
    video_url: null,
    deposit_amount: 3500000,
    monthly_fee: 3500000,
    electricity_price: 4000,
    water_price: 100000,
    internet_price: 100000,
    available_date: new Date().toISOString(),
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[0],
  },
  {
    id: 'room-2',
    building_id: '1',
    owner_id: 'owner-1',
    room_number: '201',
    floor: 2,
    area: 28,
    price: 4500000,
    room_type: '1n1k',
    status: 'available',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo', 'Tủ lạnh', 'Bếp riêng', 'Ban công'],
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3ae89?w=800',
    ],
    description: 'Phòng 1 ngủ 1 khách, bếp riêng, view phố.',
    video_url: null,
    deposit_amount: 4500000,
    monthly_fee: 4500000,
    electricity_price: 4000,
    water_price: 100000,
    internet_price: 100000,
    available_date: new Date().toISOString(),
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[0],
  },
  {
    id: 'room-3',
    building_id: '1',
    owner_id: 'owner-1',
    room_number: '305',
    floor: 3,
    area: 30,
    price: 5000000,
    room_type: '1n1k',
    status: 'deposited',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo', 'Tủ lạnh', 'Bếp riêng', 'Cửa sổ'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    description: 'Phòng cao cấp, đã có khách cọc.',
    video_url: null,
    deposit_amount: 5000000,
    monthly_fee: 5000000,
    electricity_price: 4000,
    water_price: 100000,
    internet_price: 100000,
    available_date: null,
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[0],
  },
  {
    id: 'room-4',
    building_id: '1',
    owner_id: 'owner-1',
    room_number: '401',
    floor: 4,
    area: 32,
    price: 5500000,
    room_type: '1n1k',
    status: 'rented',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo', 'Tủ lạnh', 'Bếp riêng', 'Ban công', 'Cửa sổ'],
    images: [
      'https://images.unsplash.com/photo-1522708323538-fba64bf76648?w=800',
    ],
    description: 'Phòng đã cho thuê.',
    video_url: null,
    deposit_amount: 5500000,
    monthly_fee: 5500000,
    electricity_price: 4000,
    water_price: 100000,
    internet_price: 100000,
    available_date: null,
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[0],
  },
  // Building 2 - Thanh Xuân
  {
    id: 'room-5',
    building_id: '2',
    owner_id: 'owner-1',
    room_number: '102',
    floor: 1,
    area: 20,
    price: 3200000,
    room_type: 'studio',
    status: 'available',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo'],
    images: [
      'https://images.unsplash.com/photo-1502672023488-07e099e25e68?w=800',
    ],
    description: 'Phòng studio giá tốt, phù hợp sinh viên.',
    video_url: null,
    deposit_amount: 3200000,
    monthly_fee: 3200000,
    electricity_price: 3500,
    water_price: 80000,
    internet_price: 80000,
    available_date: new Date().toISOString(),
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[1],
  },
  {
    id: 'room-6',
    building_id: '2',
    owner_id: 'owner-1',
    room_number: '203',
    floor: 2,
    area: 22,
    price: 3800000,
    room_type: 'chung_cu_mini',
    status: 'available',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo', 'Tủ lạnh'],
    images: [
      'https://images.unsplash.com/photo-1515263489006-61c0a13a153f?w=800',
    ],
    description: 'Phòng chung cư mini đẹp, gần metro.',
    video_url: null,
    deposit_amount: 3800000,
    monthly_fee: 3800000,
    electricity_price: 3500,
    water_price: 80000,
    internet_price: 80000,
    available_date: new Date().toISOString(),
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[1],
  },
  // Building 3 - Long Biên
  {
    id: 'room-7',
    building_id: '3',
    owner_id: 'owner-1',
    room_number: '501',
    floor: 5,
    area: 35,
    price: 6500000,
    room_type: 'ccmn_cao_cap',
    status: 'available',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo', 'Tủ lạnh', 'Bếp riêng', 'Ban công', 'Máy giặt riêng'],
    images: [
      'https://images.unsplash.com/photo-1460317212962-ffa3c17c6b5e?w=800',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800',
    ],
    description: 'Căn hộ cao cấp, view sông Hồng, đầy đủ tiện nghi.',
    video_url: null,
    deposit_amount: 6500000,
    monthly_fee: 6500000,
    electricity_price: 4000,
    water_price: 120000,
    internet_price: 150000,
    available_date: new Date().toISOString(),
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[2],
  },
  // Building 4 - Hà Đông
  {
    id: 'room-8',
    building_id: '4',
    owner_id: 'owner-2',
    room_number: '102',
    floor: 1,
    area: 18,
    price: 2800000,
    room_type: 'studio',
    status: 'available',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo'],
    images: [
      'https://images.unsplash.com/photo-1534237710431-e2fc698436d0?w=800',
    ],
    description: 'Phòng giá rẻ, phù hợp sinh viên các trường kinh tế, xây dựng.',
    video_url: null,
    deposit_amount: 2800000,
    monthly_fee: 2800000,
    electricity_price: 3500,
    water_price: 80000,
    internet_price: 80000,
    available_date: new Date().toISOString(),
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[3],
  },
  // Building 5 - Đống Đa
  {
    id: 'room-9',
    building_id: '5',
    owner_id: 'owner-2',
    room_number: '304',
    floor: 3,
    area: 26,
    price: 4200000,
    room_type: '1n1k',
    status: 'available',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo', 'Tủ lạnh', 'Bếp riêng'],
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    description: 'Phòng đẹp, vị trí trung tâm, dễ di chuyển.',
    video_url: null,
    deposit_amount: 4200000,
    monthly_fee: 4200000,
    electricity_price: 4000,
    water_price: 100000,
    internet_price: 100000,
    available_date: new Date().toISOString(),
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[4],
  },
  // Building 6 - Tây Hồ
  {
    id: 'room-10',
    building_id: '6',
    owner_id: 'owner-3',
    room_number: '701',
    floor: 7,
    area: 45,
    price: 12000000,
    room_type: 'can_ho_dich_vu',
    status: 'available',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo', 'Tủ lạnh', 'Bếp riêng', 'Ban công', 'Máy giặt riêng', 'Cửa sổ'],
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1c3a397171?w=800',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800',
    ],
    description: 'Căn hộ cao cấp view Hồ Tây, full nội thất, phù hợp chuyên gia nước ngoài.',
    video_url: null,
    deposit_amount: 12000000,
    monthly_fee: 12000000,
    electricity_price: 5000,
    water_price: 150000,
    internet_price: 200000,
    available_date: new Date().toISOString(),
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[5],
  },
  {
    id: 'room-11',
    building_id: '6',
    owner_id: 'owner-3',
    room_number: '702',
    floor: 7,
    area: 42,
    price: 11000000,
    room_type: 'can_ho_dich_vu',
    status: 'available',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo', 'Tủ lạnh', 'Bếp riêng', 'Ban công', 'Máy giặt riêng', 'Cửa sổ'],
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1c3a397171?w=800',
    ],
    description: 'Căn hộ cao cấp, full nội thất, view đẹp.',
    video_url: null,
    deposit_amount: 11000000,
    monthly_fee: 11000000,
    electricity_price: 5000,
    water_price: 150000,
    internet_price: 200000,
    available_date: new Date().toISOString(),
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[5],
  },
  // More rooms for Building 1
  {
    id: 'room-12',
    building_id: '1',
    owner_id: 'owner-1',
    room_number: '505',
    floor: 5,
    area: 26,
    price: 4000000,
    room_type: 'studio',
    status: 'available',
    amenities: ['Điều hòa', 'Giường', 'Tủ quần áo', 'Tủ lạnh', 'Cửa sổ'],
    images: [
      'https://images.unsplash.com/photo-1522708323538-fba64bf76648?w=800',
    ],
    description: 'Phòng tầng cao, view thoáng.',
    video_url: null,
    deposit_amount: 4000000,
    monthly_fee: 4000000,
    electricity_price: 4000,
    water_price: 100000,
    internet_price: 100000,
    available_date: new Date().toISOString(),
    last_contacted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    building: sampleBuildings[0],
  },
];

export const sampleSales = [
  {
    id: 'sale-1',
    name: 'Nguyễn Văn A',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    rating: 4.8,
    successful_deals: 45,
    response_rate: 98.5,
    phone: '0901234567',
    rank: 'gold',
  },
  {
    id: 'sale-2',
    name: 'Trần Thị B',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    rating: 4.5,
    successful_deals: 32,
    response_rate: 95.0,
    phone: '0912345678',
    rank: 'silver',
  },
  {
    id: 'sale-3',
    name: 'Lê Văn C',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    rating: 4.9,
    successful_deals: 67,
    response_rate: 99.0,
    phone: '0923456789',
    rank: 'platinum',
  },
];

export const sampleLeads = [
  {
    id: 'lead-1',
    customer_name: 'Hoàng Thị D',
    customer_phone: '0934567890',
    room_id: 'room-1',
    status: 'new',
    last_contacted_at: new Date(Date.now() - 86400000).toISOString(),
    sale_id: 'sale-1',
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'lead-2',
    customer_name: 'Phạm Văn E',
    customer_phone: '0945678901',
    room_id: 'room-5',
    status: 'consulting',
    last_contacted_at: new Date(Date.now() - 3600000).toISOString(),
    sale_id: 'sale-1',
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'lead-3',
    customer_name: 'Nguyễn Văn F',
    customer_phone: '0956789012',
    room_id: 'room-7',
    status: 'scheduled',
    last_contacted_at: new Date(Date.now() - 7200000).toISOString(),
    sale_id: 'sale-1',
    created_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: 'lead-4',
    customer_name: 'Lê Thị G',
    customer_phone: '0967890123',
    room_id: 'room-2',
    status: 'viewed',
    last_contacted_at: new Date().toISOString(),
    sale_id: 'sale-1',
    created_at: new Date(Date.now() - 432000000).toISOString(),
  },
];

export const sampleAppointments = [
  {
    id: 'apt-1',
    lead_id: 'lead-3',
    sale_id: 'sale-1',
    room_id: 'room-7',
    customer_name: 'Nguyễn Văn F',
    customer_phone: '0956789012',
    scheduled_at: new Date(Date.now() + 86400000).toISOString(),
    status: 'scheduled',
    notes: 'Khách muốn xem phòng vào buổi chiều',
  },
  {
    id: 'apt-2',
    lead_id: 'lead-4',
    sale_id: 'sale-1',
    room_id: 'room-2',
    customer_name: 'Lê Thị G',
    customer_phone: '0967890123',
    scheduled_at: new Date(Date.now() + 172800000).toISOString(),
    status: 'scheduled',
    notes: '',
  },
];

export const sampleDeposits = [
  {
    id: 'deposit-1',
    room_id: 'room-3',
    sale_id: 'sale-1',
    owner_id: 'owner-1',
    lead_id: 'lead-3',
    customer_name: 'Nguyễn Văn H',
    customer_phone: '0978901234',
    customer_email: 'nguyenvanh@email.com',
    deposit_amount: 5000000,
    status: 'pending',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'deposit-2',
    room_id: 'room-4',
    sale_id: 'sale-1',
    owner_id: 'owner-1',
    lead_id: 'lead-4',
    customer_name: 'Lê Thị I',
    customer_phone: '0989012345',
    customer_email: 'lethi@email.com',
    deposit_amount: 5500000,
    status: 'approved',
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
];

export const sampleCommissions = [
  {
    id: 'comm-1',
    deposit_id: 'deposit-2',
    sale_id: 'sale-1',
    owner_id: 'owner-1',
    room_id: 'room-4',
    commission_rate: 10,
    commission_amount: 550000,
    status: 'pending',
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
];
